### ISSUE TITLE
Use GitHub Actions instead of Docker Cloud?

### ISSUE THREAD

**Issue by humenius** [humenius/traefik-certs-dumper#22]
Depending on #21, I don't know if it is possible to build multi-arch images on Docker cloud. In case that is true, maybe we can use GitHub Actions, travis or something else.

**Comment by rfgamaral** [comment]
I used to use DockerHub to build multi-arch images (I believe it's the same thing you refer to as Docker Cloud) but you also need to create a manifest file that I'm not quite sure you can do with DockerHub. I've since migrated to GitHub Actions myself to do all that.

I use a custom solution with a few custom scripts to do that but I believe nowadays there are some pre-built actions you can use to simplify the process. I personally recommend GitHub Actions for this, they're awesome.

**Comment by humenius** [comment]
Still working on it

**Comment by humenius** [comment]
Still working on it!

**Comment by humenius** [comment]
I guess this should be done now. The actions for tagging and labeling should work. But I guess we can only see if it works by using it once. :)
