### ISSUE TITLE
Introduction of a slim variant

### ISSUE THREAD

**Issue by humenius** [humenius/traefik-certs-dumper#8]
I just noticed that there's a huge jump in container file size between version 1.0 and 1.1.
It is probably caused by using the Docker image as the cert dumper includes container restart feature.
Maybe we could introduce a slim image which bases on an Alpine image. This would also mean that the container restart feature will be unavailable.

Possible solution:
1. Extract `restart_container` logic into separate shell script file and source it if the container can find it.
2. Create 2nd `Dockerfile` for slim version specifically.
3. We could use a naming convention like:
```
(latest,) alpine, {VERSION}-alpine - Alpine / slim version
(latest,) dnd, {VERSION}-dnd - Image with Docker + Restart Container feature
```

Also, we should think about which one of the image should be the "main" image receiving the `latest` tag.

**EDIT**: Something worth mentioning is [DockerSlim](https://github.com/docker-slim/docker-slim).

**Comment by bartagergely** [comment]
First of all: Thank you for your great work. This image helped me to use mailcow on a shared host, without losing the ability to use port80. 
I am not using my scenario for more than 3 months (So I did hot have a cert-renewal yet), but based on the lot of text I found on different forums, container-restart is an important function (for me at least :-) )
In my opinion different naming (alpine, dnd) looks as the best solution, and the main (latest) should be the full version.

**Comment by rfgamaral** [comment]
I have a suggestion regarding the "restart containers" functionality that I'm not sure if it impacts this issue so I'm posting here instead of creating a new issue. Hope that's okay with you :)

Instead of relying on the `command` to specify the container names to restart when certs changed, what do you think of using labels instead? Similar to what [this one](https://github.com/SnowMB/traefik-certificate-extractor). Doesn't need to be exactly like that project is doing, we can adapt the way it works if needed; it's just an example. What I like about approach is that you configure the container you want restarted in the container itself, instead of the current approach where you configure all the containers you want restarted in a single container (the certs dumper). What do you think?

**Comment by humenius** [comment]
Yes, I agree with the usage of scanning for labels instead of using `command`. I think I implemented it this way because I didn't want to go through the hassle of filtering Docker containers for their labels.

But well, shouldn't be a hassle. Actually easy by using something similar:
```bash
$ docker inspect -f '{{ index .Config.Labels "$labelname" }}' $(sudo docker ps -aq)
```

This just display all values of label `$labelname`. We probably have to fetch all available containers with `docker ps`, `docker inspect` and if a value for `$labelname` is present, add ID to array of containers to be restarted.

We might need a good label name, something like `me.humenius.traefik-certs.restart`.
